[tool.poetry]
name = "investment-funnel"
version = "0.0.0"
description = "Open-source testing and benchmarking plaform for asset allocation."
authors = ["Petr Vanek"]
readme = "README.md"
repository = "https://github.com/VanekPetr/investment-funnel"
homepage = "https://investment-funnel.algostrata.com"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pandas = "2.2.2"
pandas-datareader = "0.10.0"
dash = "2.16.1"
dash-bootstrap-components = "1.6.0"
plotly = "5.21.0"
plotly-express = "0.4.1"
python-dateutil = "2.9.0.post0"
pulp = "2.8.0"
numpy = "1.26.4"
networkx = "3.2.1"
matplotlib = "3.8.4"
scikit-learn = "1.4.2"
scipy = "1.13.0"
pyarrow = "16.0.0"
yfinance = "0.2.38"
loguru = "0.7.2"
joblib = "1.4.0"
gunicorn = "22.0.0"
python-dotenv = "1.0.1"
cvxpy = "1.4.3"
arch = "7.0.0"
pydantic = "2.7.1"
pydantic-settings = "2.2.1"
tqdm = "4.66.2"
pre-commit = "3.7.0"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"
pre-commit = "*"

[build-system]
requires = ["poetry>=1.6.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.select = ["E", "F", "I"]
line-length = 120
target-version = "py310"
exclude = [
    "*__init__.py"
]
