[tool.poetry]
name = "investment-funnel"
version = "0.0.0"
description = "Open-source testing and benchmarking plaform for asset allocation."
authors = ["Petr Vanek"]
readme = "README.md"
repository = "https://github.com/VanekPetr/investment-funnel"
homepage = "https://investment-funnel.algostrata.com"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pandas = "2.2.0"
pandas-datareader = "0.10.0"
dash = "2.15.0"
dash-bootstrap-components = "1.5.0"
plotly = "5.18.0"
plotly-express = "0.4.1"
python-dateutil = "2.8.2"
pulp = "2.8.0"
numpy = "1.26.4"
networkx = "3.2.1"
matplotlib = "3.8.2"
scikit-learn = "1.4.1.post1"
scipy = "1.12.0"
pyarrow = "15.0.0"
yfinance = "0.2.36"
loguru = "0.7.2"
joblib = "1.3.2"
gunicorn = "21.2.0"
python-dotenv = "1.0.1"
cvxpy = "1.4.2"
pydantic = "2.6.1"
pydantic-settings = "2.2.0"
tqdm = "4.66.2"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"
pre-commit = "*"

[build-system]
requires = ["poetry>=1.6.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "I"]
line-length = 120
target-version = "py310"
exclude = [
    "*__init__.py"
]
