[tool.poetry]
name = "investment-funnel"
version = "0.0.0"
description = "Open-source testing and benchmarking plaform for asset allocation."
authors = ["Petr Vanek"]
readme = "README.md"
repository = "https://github.com/VanekPetr/investment-funnel"
homepage = "https://investment-funnel.algostrata.com"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pandas = "2.2.2"
pandas-datareader = "0.10.0"
dash = "2.17.1"
dash-bootstrap-components = "1.6.0"
plotly = "5.23.0"
plotly-express = "0.4.1"
python-dateutil = "2.9.0.post0"
pulp = "2.9.0"
numpy = "1.26.4"
networkx = "3.3"
matplotlib = "3.9.0"
scikit-learn = "1.5.1"
scipy = "1.14.0"
pyarrow = "17.0.0"
yfinance = "0.2.41"
loguru = "0.7.2"
joblib = "1.4.0"
gunicorn = "22.0.0"
python-dotenv = "1.0.1"
cvxpy-base = "1.5.2"
ecos = "*"
clarabel = "*"
arch = "7.0.0"
pydantic = "2.8.2"
pydantic-settings = "2.4.0"
tqdm = "4.66.5"
pre-commit = "3.8.0"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"
pre-commit = "*"

[build-system]
requires = ["poetry>=1.7.1"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.select = ["E", "F", "I"]
line-length = 120
target-version = "py310"
exclude = [
    "*__init__.py"
]
