# Run pre-commit on all files in the repository
name: pre-commit

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1
      with:
          extra_args: '--verbose --all-files'

  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/uv/environment@v2.1.0
        
      - uses: cvxgrp/.github/actions/deptry@v2.1.0
        with:
          source-folder: 'funnel'
