# Run pre-commit on all files in the repository
name: pre-commit

on:
  push:

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cvxgrp/.github/actions/uv/deptry@v2.0.7
        with:
          source-folder: 'funnel'
