name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/uv/environment@v2.2.3

      - uses: cvxgrp/.github/actions/coverage@v2.2.3
        with:
          source-folder: 'funnel'
